version: '3'

services:
  app:
    build: .
    depends_on:
      - 'database'
      - 'redis'
    ports:
      - '3100:3100'
  database: 
    image: 'postgres'
    container_name: 'friendly_meitner'
    ports:
      - '5432:5432/tcp'
  redis:
    image: 'redis'
    container_name: 'redis-devel'
    ports: 
      - '6379:6379/tcp'